# Generated by Django 5.2.6 on 2025-09-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="iota_block_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="iota_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="iota_stored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificate",
            name="iota_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="iota_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
